In [1]:
import torch

In [2]:
a=torch.rand(16,128,768)

In [3]:
a

tensor([[[5.7170e-01, 8.3388e-01, 3.2113e-01,  ..., 8.3440e-01,
          4.0457e-01, 1.2088e-02],
         [5.1448e-01, 4.9070e-01, 2.7788e-02,  ..., 9.9852e-03,
          4.8967e-01, 5.8924e-01],
         [1.7839e-01, 8.6469e-01, 3.3628e-01,  ..., 4.7741e-01,
          5.5622e-01, 6.6893e-01],
         ...,
         [6.2034e-01, 8.7726e-01, 7.1582e-01,  ..., 6.3082e-01,
          6.5434e-02, 9.0705e-01],
         [1.7386e-01, 2.9355e-01, 8.1914e-01,  ..., 3.1759e-01,
          7.6744e-01, 6.4002e-01],
         [6.5992e-01, 5.7413e-01, 1.3200e-01,  ..., 6.5854e-01,
          4.3285e-01, 1.3352e-01]],

        [[7.6541e-01, 7.4223e-02, 7.9101e-01,  ..., 4.2775e-01,
          2.5781e-01, 6.8415e-01],
         [7.2672e-01, 9.3174e-01, 7.6709e-01,  ..., 3.7623e-01,
          9.0117e-01, 8.1868e-01],
         [4.4314e-01, 4.3860e-01, 8.8561e-01,  ..., 1.8458e-02,
          2.8318e-01, 6.6270e-03],
         ...,
         [9.5570e-01, 1.1295e-01, 4.8095e-01,  ..., 4.7556e-02,
          3.141

In [4]:
a.shape

torch.Size([16, 128, 768])

In [ ]:
a=torch.rand(16,128,768)

In [8]:
torch.transpose(a,0,1)

tensor([[[5.7170e-01, 8.3388e-01, 3.2113e-01,  ..., 8.3440e-01,
          4.0457e-01, 1.2088e-02],
         [7.6541e-01, 7.4223e-02, 7.9101e-01,  ..., 4.2775e-01,
          2.5781e-01, 6.8415e-01],
         [4.0658e-01, 1.4486e-01, 5.6513e-01,  ..., 3.9037e-01,
          5.5110e-02, 2.9291e-01],
         ...,
         [7.4255e-01, 6.6674e-02, 9.8185e-02,  ..., 5.2361e-02,
          8.1759e-01, 7.8070e-01],
         [5.8294e-01, 6.5770e-01, 6.5585e-02,  ..., 5.5550e-01,
          1.8603e-02, 9.6343e-01],
         [7.1104e-01, 2.9863e-01, 9.9209e-01,  ..., 6.5507e-01,
          9.1457e-04, 2.1723e-01]],

        [[5.1448e-01, 4.9070e-01, 2.7788e-02,  ..., 9.9852e-03,
          4.8967e-01, 5.8924e-01],
         [7.2672e-01, 9.3174e-01, 7.6709e-01,  ..., 3.7623e-01,
          9.0117e-01, 8.1868e-01],
         [3.7927e-01, 2.4281e-01, 8.3471e-01,  ..., 7.3338e-01,
          8.4551e-01, 9.8028e-01],
         ...,
         [6.8434e-01, 6.5512e-01, 3.9985e-01,  ..., 5.0147e-01,
          6.285

In [9]:
a=torch.rand(3,4,5)

In [17]:
a[0]

tensor([[0.7326, 0.1738, 0.2068, 0.0761, 0.8004],
        [0.8633, 0.9452, 0.6494, 0.9322, 0.1608],
        [0.0188, 0.0044, 0.0388, 0.2823, 0.9389],
        [0.3562, 0.0116, 0.0051, 0.0082, 0.5083]])

In [12]:
at=torch.transpose(a,0,1)

In [15]:
at.shape

torch.Size([4, 3, 5])

In [16]:
at

tensor([[[0.7326, 0.1738, 0.2068, 0.0761, 0.8004],
         [0.4821, 0.5550, 0.0255, 0.5292, 0.7310],
         [0.8258, 0.2679, 0.8239, 0.6523, 0.1510]],

        [[0.8633, 0.9452, 0.6494, 0.9322, 0.1608],
         [0.7076, 0.5414, 0.9449, 0.6333, 0.8635],
         [0.2051, 0.9050, 0.4534, 0.5149, 0.8710]],

        [[0.0188, 0.0044, 0.0388, 0.2823, 0.9389],
         [0.5594, 0.4947, 0.9840, 0.1916, 0.2762],
         [0.2070, 0.6860, 0.3687, 0.3902, 0.5387]],

        [[0.3562, 0.0116, 0.0051, 0.0082, 0.5083],
         [0.2349, 0.2067, 0.7027, 0.8176, 0.5667],
         [0.1997, 0.3690, 0.6302, 0.9632, 0.4520]]])

In [18]:
a

tensor([[[0.7326, 0.1738, 0.2068, 0.0761, 0.8004],
         [0.8633, 0.9452, 0.6494, 0.9322, 0.1608],
         [0.0188, 0.0044, 0.0388, 0.2823, 0.9389],
         [0.3562, 0.0116, 0.0051, 0.0082, 0.5083]],

        [[0.4821, 0.5550, 0.0255, 0.5292, 0.7310],
         [0.7076, 0.5414, 0.9449, 0.6333, 0.8635],
         [0.5594, 0.4947, 0.9840, 0.1916, 0.2762],
         [0.2349, 0.2067, 0.7027, 0.8176, 0.5667]],

        [[0.8258, 0.2679, 0.8239, 0.6523, 0.1510],
         [0.2051, 0.9050, 0.4534, 0.5149, 0.8710],
         [0.2070, 0.6860, 0.3687, 0.3902, 0.5387],
         [0.1997, 0.3690, 0.6302, 0.9632, 0.4520]]])

In [33]:
a=torch.rand(768)

In [34]:
a

tensor([4.8793e-01, 5.4629e-02, 7.9210e-02, 7.4354e-01, 5.7052e-03, 7.0005e-01,
        4.2525e-01, 4.3485e-01, 6.9438e-01, 8.1429e-01, 3.1595e-01, 7.3981e-01,
        6.6985e-01, 1.8199e-02, 2.4382e-01, 7.8755e-01, 1.2697e-01, 3.4407e-01,
        3.5859e-01, 6.4822e-02, 6.0237e-01, 1.1652e-01, 9.5689e-01, 4.2968e-01,
        5.5575e-01, 6.8060e-01, 5.1073e-01, 1.2724e-01, 3.9365e-01, 4.9933e-01,
        8.4691e-01, 1.7320e-01, 3.8399e-01, 4.7443e-01, 8.4793e-01, 3.0843e-01,
        1.7766e-01, 9.4230e-01, 8.4539e-01, 3.2883e-02, 9.1410e-01, 3.1102e-01,
        1.3725e-01, 9.5608e-02, 2.5608e-01, 1.3123e-02, 6.2552e-01, 1.4257e-01,
        4.9253e-01, 4.1190e-01, 5.6115e-01, 2.8622e-02, 6.0523e-02, 3.8847e-01,
        1.0453e-01, 2.0140e-01, 2.8212e-01, 1.6604e-01, 6.5349e-01, 5.4942e-01,
        9.9594e-01, 7.1788e-01, 8.5483e-02, 5.9974e-01, 5.7943e-01, 2.3088e-01,
        8.3395e-01, 9.5471e-01, 1.3441e-01, 6.8881e-01, 6.7231e-01, 4.1762e-01,
        7.0585e-01, 8.0464e-01, 5.9324e-

In [35]:
b=torch.rand(768)

In [36]:
b

tensor([0.6435, 0.7626, 0.7392, 0.3101, 0.0655, 0.2635, 0.2840, 0.4703, 0.8667,
        0.1478, 0.8674, 0.8269, 0.7284, 0.4645, 0.2155, 0.9328, 0.6738, 0.8534,
        0.6878, 0.4974, 0.8349, 0.3115, 0.8648, 0.4596, 0.9878, 0.6098, 0.9015,
        0.1379, 0.2157, 0.8474, 0.5857, 0.2456, 0.8463, 0.2542, 0.7209, 0.5407,
        0.3293, 0.4618, 0.3216, 0.8926, 0.2712, 0.2923, 0.6681, 0.0430, 0.0971,
        0.1713, 0.6678, 0.0767, 0.1816, 0.9252, 0.1986, 0.8571, 0.9841, 0.3912,
        0.5193, 0.6624, 0.8493, 0.5050, 0.1914, 0.7620, 0.0033, 0.2237, 0.8693,
        0.5377, 0.1600, 0.4832, 0.6605, 0.8203, 0.5254, 0.0141, 0.4551, 0.0695,
        0.1344, 0.1468, 0.1605, 0.3816, 0.4205, 0.8936, 0.2272, 0.8867, 0.9776,
        0.1767, 0.9008, 0.7780, 0.5304, 0.9750, 0.2731, 0.9075, 0.8294, 0.3361,
        0.5925, 0.5975, 0.4258, 0.4902, 0.7239, 0.1924, 0.3419, 0.1689, 0.9399,
        0.4930, 0.9635, 0.6532, 0.6426, 0.4287, 0.8474, 0.6506, 0.6010, 0.4099,
        0.4583, 0.9360, 0.7366, 0.4424, 

In [38]:
b=torch.cat((a,b),0)

In [39]:
b.shape

torch.Size([1536])